FROM debian:bookworm

RUN apt-get -y update
RUN apt-get -y install --no-install-recommends \
    linux-image-amd64
RUN apt-get -y install xorriso grub-pc-bin grub-common

WORKDIR /output
COPY ./iso ./iso
COPY ./init .

# Put all to /strelkasys
# Generates something in /output
RUN mkdir /strelkasys
RUN mkdir /strelkasys/initrd
WORKDIR /strelkasys/initrd
RUN mkdir -p bin dev mnt proc sys tmp sbin lib

RUN cp -rf /bin/* /strelkasys/initrd/bin
#RUN cp -rf /lib/* /strelkasys/initrd/lib
RUN ldd /bin/sh | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp -v '{}' /strelkasys/initrd/lib
RUN cp /output/init /strelkasys/initrd
RUN chmod +x /strelkasys/initrd/init

RUN find . | cpio -R root:root -H newc -o | gzip > /strelkasys/rootfs.gz

RUN cp /strelkasys/rootfs.gz /output/iso/boot
RUN cp /vmlinuz /output/iso/boot
RUN cp -rf /strelkasys/initrd/* /output/iso
RUN grub-mkrescue /usr/lib/grub/i386-pc -o /output/strelka.iso /output/iso

CMD cp /output/strelka.iso /vol

