# Linux build example
# https://github.com/masoudr/embedded-linux-image-builder

FROM debian:bookworm

RUN apt-get -y update
RUN apt-get -y install --no-install-recommends \
    linux-image-amd64
RUN apt-get -y install xorriso grub-pc-bin grub-common
RUN apt-get install -y dpkg multistrap debian-archive-keyring


RUN mkdir /initrd
WORKDIR /initrd
RUN mkdir -p bin dev mnt proc sys tmp sbin lib usr/bin usr/lib
RUN cp -rf /bin/* /initrd/bin
RUN cp -rf /lib/* /initrd/lib
RUN cp -rf /usr/* /initrd/usr
# RUN ldd /bin/sh | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp -v '{}' /initrd/lib
# RUN ldd /usr/bin/dpkg | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp -v '{}' /initrd/lib

#RUN debootstrap stable /initrd http://deb.debian.org/debian/

COPY ./multistrap.conf /build/multistrap.conf
RUN cat usr/sbin/multistrap && multistrap -d /initrd -f /build/multistrap.conf
# https://github.com/volumio/Build/issues/348

COPY ./init ./initrd
COPY ./xinitrc ./initrd

RUN mkdir -p /output/iso/boot

RUN find . | cpio -R root:root -H newc -o | gzip > /output/iso/boot/rootfs.gz

RUN cp /boot/vmlinuz /output/iso/boot

RUN grub-mkrescue /usr/lib/grub/i386-pc -o /output/strelka.iso /output/iso

CMD cp /output/strelka.iso /vol