Section "InputDevice"
    Identifier "Mouse1"
    Driver "mouse"
    Option "Protocol" "Auto"
    Option "Device" "/dev/input/mice"
    Option "ZAxisMapping" "4 5"
    Option "Resolution" "800"
EndSection